# fly.toml app configuration file generated for dcreactivities on 2023-07-14T14:00:05-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dcreactivities"
primary_region = "atl"

[build]
  image = "dustinc027/reactivities:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  Cloudinary__CloudName="dpseikuqn"
  Cloudinary__ApiKey="822448657549684"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
